config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :members, controllers: { registrations: 'members/registrations', sessions: 'members/sessions' }
  devise_scope :member do
    get 'members/sign_out' => 'members/sessions#destroy'
    get 'members'          => 'members#index'
    post 'member/email_info' => 'members/registrations#email'
  end

  resources :messages, only: [:create] # TODO - this controller doesn't exist
  get '/rush' => 'rush#index'
  get '/tweets' => 'tweets#index'
  namespace :calendar do
    resources :events, only: %i[index show]
  end
  get '/calendar' => 'calendar/events#index'

  get '/projects/:project_id/donations/new' => 'donations#new'
  get '/projects/:project_id/donations'     => 'donations#index'
  post '/projects/:project_id/donations'    => 'donations#create'
  get '/projects_and_donations'             => 'projects#index'
  resources :projects, only: [:edit, :create, :destroy, :update] do
    post '/complete'                        => 'projects#complete'
  end
  get '/alumni'                             => 'alumni#index'
  resources 'roles', only: %i[edit update]
  resources 'pictures', only: %i[create destroy]
  resources 'unassociated_pictures', only: %i[create destroy]
  get '/profile'                            => 'members#edit'
  patch '/profile'                          => 'members#update'
  get '/members/sign_out'                   => 'members/sessions#destroy'

  namespace :forum do
    get '/'                              => 'channels#index'
    resources :channels, only: [:create, :update, :new, :destroy, :show] do
      resources :posts, only: [:create, :update, :destroy] do
        resources :reactions, only: [:create, :destroy]
      end
    end
  end
  if Rails.env.production?
    require 'sidekiq/web'
    authenticate :member, lambda { |m| m.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/views/active_officers/_edit.html.erb
<%= image_tag role.member.profile_picture, class: 'officer-picture' %>
<div class = 'info-container'>
  <%= form_for role, authenticity_token: true, remote: true, url: role_path(role, format: :js) do |f| %>
    <%= f.hidden_field :role_type %>
    <%= f.hidden_field :title %>
    <span class='officer-name'>
      <%= select_tag 'role[member_id]', options_from_collection_for_select(members, "id", "full_name", role.member.id), onchange: "$(this).closest('form').trigger('submit.rails');" %>
    </span>
    <span class='officer-title'><%= role.title.titleize %></span>
    <span class='officer-email'><%= mail_to role.member.email %></span>
    <span class='officer-phone'>
      <%= link_to role.member.phone_number, "tel:#{role.member.phone_number}" if role.member.phone_number %>
    </span>
  <% end %>
</div>

app/views/active_officers/_index.html.erb
<div id='officers' class='container-fluid container-lg-padded'>
  <h4><strong>OFFICERS</strong></h4>
  <p> These are our elected officials for the <%=Date.today.year%> calendar year </p>
  <div class='row'>
    <% @active_roles.each do |role| %>
      <div class='officer-container col-xs-12 col-md-3' data-role-id=<%=role.id%>>
        <%= render 'active_officers/show', role: role %>
      </div>
      <hr class = 'officer-separator'/>
    <% end %>
  </div>
</div>

app/views/active_officers/_show.html.erb
<%= image_tag role.member.profile_picture, class: 'officer-picture' %>
<div class = 'info-container'>
  <% if @admin_flag %>
    <%= link_to edit_role_path(role), remote: true, method: :get, class: 'edit-officer pull-right' do %>
      <i class = 'fa fa-edit'></i>
    <% end %>
  <% end %>
  <span class='officer-name'><%= role.member.full_name.upcase %></span>
  <span class='officer-title'><%= role.title.titleize %></span>
  <span class='officer-email'><%= mail_to role.member.email %></span>
  <span class='officer-phone'>
    <%= link_to role.member.phone_number, "tel:#{role.member.phone_number}" if role.member.phone_number %>
  </span>
</div>

app/views/active_officers/edit.js.erb
$('[data-role-id=<%=@role.id%>]').html('<%= j render('active_officers/edit', role: @role, members: @members)%>')

app/views/active_officers/update.js.erb
$('[data-role-id=<%=@role.id%>]').html('<%= j render('active_officers/show', role: @role)%>')