config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :members, controllers: { registrations: 'members/registrations', sessions: 'members/sessions' }
  devise_scope :member do
    get 'members/sign_out' => 'members/sessions#destroy'
    get 'members'          => 'members#index'
    post 'member/email_info' => 'members/registrations#email'
  end

  resources :messages, only: [:create] # TODO - this controller doesn't exist
  get '/rush' => 'rush#index'
  get '/tweets' => 'tweets#index'
  namespace :calendar do
    resources :events, only: %i[index show]
  end
  get '/calendar' => 'calendar/events#index'

  get '/projects/:project_id/donations/new' => 'donations#new'
  get '/projects/:project_id/donations'     => 'donations#index'
  post '/projects/:project_id/donations'    => 'donations#create'
  get '/projects_and_donations'             => 'projects#index'
  resources :projects, only: [:edit, :create, :destroy, :update] do
    post '/complete'                        => 'projects#complete'
  end
  get '/alumni'                             => 'alumni#index'
  resources 'roles', only: %i[edit update]
  resources 'pictures', only: %i[create destroy]
  resources 'unassociated_pictures', only: %i[create destroy]
  get '/profile'                            => 'members#edit'
  patch '/profile'                          => 'members#update'
  get '/members/sign_out'                   => 'members/sessions#destroy'

  namespace :forum do
    get '/'                              => 'channels#index'
    resources :channels, only: [:create, :update, :new, :destroy, :show] do
      resources :posts, only: [:create, :update, :destroy] do
        resources :reactions, only: [:create, :destroy]
      end
    end
  end
  if Rails.env.production?
    require 'sidekiq/web'
    authenticate :member, lambda { |m| m.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/forum/channel.rb
module Forum
  class Channel < ActiveRecord::Base
    has_many :posts
    has_and_belongs_to_many :members, join_table: 'channel_members'
    scope :publik, -> { where(visibility: 'public') }

    def self.nil_channel
      new(id: -1)
    end

    def publik?
      visibility == 'public'
    end

    def visible_to?(member)
      publik? ||
        self.class.connection.select_value("SELECT #{member.id} IN (#{members.select(:member_id).to_sql})") == 't'
    end

    def member_count
      # TODO: this is a temporary method, until I figure out what exactly 'joining a channel' looks like
      @member_count ||= posts.select(:author_id).uniq.count
    end
  end
end

app/models/forum/post.rb
module Forum
  class Post < ActiveRecord::Base
    include TimeFormatHelper

    validates  :content, :author_id, :channel_id, presence: true
    belongs_to :author, class_name: 'Member'
    belongs_to :channel
    belongs_to :parent, class_name: 'Forum::Post'
    has_many   :replies, class_name: 'Forum::Post', foreign_key: 'parent_id'
    has_many   :reactions
    has_many   :notifications
    after_commit :create_notification
    around_update :update_notifications
    after_destroy :acknowledge_notifications

    def formatted_updated_at # rubocop:disable Metrics/AbcSize
      # TODO: this is poorly implemented and mislocated and.. I'm feeling lazy
      if updated_at.to_date == Time.zone.today
        updated_at.localtime.strftime(clock_time_format)
      elsif updated_at.to_date > Time.zone.today - 7.days
        updated_at.localtime.strftime(this_week_format)
      elsif updated_at.year > Time.zone.today.year
        updated_at.localtime.strftime(this_year_format)
      else
        updated_at.localtime.strftime(legible_timestamp_format)
      end
    end

    def tagged_members(c = content)
      matches = c.scan(/(?:^| )@([\w.]*)/).flatten
      return [] unless matches.present?
      screen_names = matches.map { |name| name.strip.chomp('.') }
      Member.where(screen_name: screen_names)
    end

    private

    def notification_recipients(c = content)
      return tagged_members(c) if tagged_members(c).empty?
      tagged_members(c).where.not(member_id: author_id)
    end

    def create_notification
      ForumNotificationWorker.perform_async(id, notification_recipients.map(&:member_id))
    end

    def update_notifications
      previous_notification_recipients = notification_recipients(changes['content'][0]).map(&:member_id)
      yield
      new_notification_recipients = notification_recipients.map(&:member_id)
      added_tags = new_notification_recipients - previous_notification_recipients
      removed_tags = previous_notification_recipients - new_notification_recipients
      notifications.where(recipient_id: removed_tags).update_all(acknowledged: true)
      ForumNotificationWorker.perform_async(id, added_tags)
    end

    def acknowledge_notifications
      notifications.update_all(acknowledged: true)
    end
  end
end

app/models/forum/reaction.rb
module Forum
  class Reaction < ActiveRecord::Base
    validates :reaction_text, :member_id, :post_id, presence: true
    belongs_to :member
    belongs_to :post
  end
end

app/controllers/forum/channels_controller.rb
module Forum
  class ChannelsController < ApplicationController
    before_action :store_location, :authenticate_member!
    before_action :acknowledge_notifications, only: :show

    def index
      @current_channel = channel_from_session || default_channel
      # TODO: add scope for public + private channels I can see
      session[:channel_id] = @current_channel.id
      @all_channels = Forum::Channel.publik.select(:subject, :channel_id)
      @posts = posts
    end

    def show
      @current_channel ||= Forum::Channel.find(params[:id])
      session[:channel_id] = params[:id]
      @posts = posts(@current_channel)
      @all_channels = Forum::Channel.publik.select(:subject, :channel_id)
      respond_to do |format|
        format.js
        format.html
      end
    end

    def create
      @current_channel = Forum::Channel.where('lower(subject) = ?', channel_params[:subject]).first
      @current_channel ||= Forum::Channel.create(channel_params)
      @posts = []
    end

    private

    def default_channel
      return @default_channel unless @default_channel.nil?
      channel = Forum::Post.select('count(*)', :channel_id).group(:channel_id).order(count: :desc).first
      return Forum::Channel.nil_channel unless channel
      most_active_channel = Forum::Channel.find(channel.channel_id)
      return @default_channel = most_active_channel if most_active_channel.publik?
      @default_channel = Forum::Channel.publik.order(:created_at).first
    end

    def channel_from_session
      Forum::Channel.find(session[:channel_id]) if session[:channel_id]
    rescue ActiveRecord::RecordNotFound
      nil
    end

    def posts(channel = default_channel)
      Forum::Post.includes(:author, :reactions, replies: [:author, :reactions, replies: [:author, :reactions]]).
        where(channel_id: channel.id, depth: 0).order(:created_at)
    end

    def channel_params
      params.require(:forum_channel).permit(:subject, :description, :visibility)
    end

    def store_location
      store_location_for(:member, request.path)
    end

    def acknowledge_notifications
      @current_channel ||= Forum::Channel.find(params[:id])
      Notification.joins('JOIN POSTS p ON(notifications.post_id = p.post_id)
                          JOIN channels c ON (c.channel_id = p.channel_id)').
        where("c.channel_id = #{@current_channel.id}").
        update_all(acknowledged: true)
    end
  end
end

app/controllers/forum/posts_controller.rb
module Forum
  class PostsController < ApplicationController
    before_action :authenticate_member!, :verify_visibility

    def create
      @post = Forum::Post.create!(post_params)
      @parent_id = parent.try(:id)
    rescue ActiveRecord::RecordInvalid => e
      render json: { errors: e.message }, status: :not_acceptable
    end

    def update
      @post = Forum::Post.find_by!(post_params.except(:content, :depth))
      @post.update(content: post_params[:content])
    rescue ActiveRecord::RecordInvalid => e
      render json: { errors: e.message }, status: :not_acceptable
    end

    def destroy
      @post = Forum::Post.find(params[:id])
      if @post.author_id != current_member.id
        render json: { errors: 'not allowed' }, status: :forbidden
      else
        @post.destroy!
      end
    end

    private

    def verify_visibility
      render :nothing, status: 403 and return unless channel.visible_to?(current_member)
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "We're sorry, something went wrong with saving your post"
      render 'error', status: 404
      flash.delete(:alert)
      # TODO: notify error watchers
    end

    def channel
      @channel ||= Forum::Channel.find(params[:channel_id])
    end

    def post_params
      params.permit(:content, :channel_id, :parent_id).merge(
        author_id: current_member.id,
        depth: depth,
        post_id: params[:id]
      )
    end

    def parent
      return if params[:parent_id].blank?
      @parent ||= Forum::Post.find(params[:parent_id])
    end

    def depth
      parent.nil? ? 0 : parent.depth + 1
    end
  end
end

app/controllers/forum/reactions_controller.rb
module Forum
  class ReactionsController < ApplicationController
    before_action :authenticate_member!, :check_permissions, :check_associations

    def create
      @reaction = Forum::Reaction.create(reaction_params)
      @post = @reaction.post
    end

    def destroy
      @reaction = Forum::Reaction.find_by(reaction_params).destroy
      @post = @reaction.post
    end

    private

    def reaction_params
      { member_id: current_member.id,
        post_id: params.require(:post_id),
        reaction_id: params[:id],
        reaction_text: 'Like'
      }
    end

    def check_permissions
      unless Forum::Channel.find(params[:channel_id]).visible_to? current_member
        render nothing: true, status: :unauthorized
      end
    end

    def check_associations
      channel = Forum::Channel.includes(:posts).find(params[:channel_id])
      unless channel.posts.pluck(:post_id).include? params.require(:post_id).to_i
        render nothing: true, status: :unauthorized
      end
    end
  end
end

app/views/forum/posts/_edit.html.erb
<%= form_tag forum_channel_posts_path(channel.id), method: :put, remote: true do %>
  <%= hidden_field_tag request_forgery_protection_token.to_s, form_authenticity_token %>
  <%= hidden_field_tag :channel_id, channel.id %>
  <%= text_area_tag    :content, '', class: 'edit-post-content taggit' %>
<% end %>

app/views/forum/posts/_new.html.erb
<div class = 'new-post'>
  <%= form_tag forum_channel_posts_path(channel.id), remote: true do %>
    <%= hidden_field_tag request_forgery_protection_token.to_s, form_authenticity_token %>
    <%= hidden_field_tag :parent_id %>
    <%= text_area_tag   :content, '', placeholder: "Post in ##{channel.subject}", class: 'new-post-content taggit' %>
  <% end %>
</div>

app/views/forum/posts/_reply.html.erb
<div class = 'col-xs-11 post-reply'>
  <%= render 'forum/posts/show', post: reply %>
</div>

app/views/forum/posts/_show.html.erb
<div class = 'row' data-post-id ="<%=post.id%>">
  <div class = 'col-xs-12'>
    <div class = 'post'>
      <div class = 'post-metadata'>
        <span class = 'post-author-name'><%= post.author.full_name %></span>
        <span class = 'vertical-divider'> | </span>
        <span class = 'post-created-at' ><%= post.formatted_updated_at %></span>
      </div>
      <p class = 'post-content'><%= post.content %></p>
      <div class = 'post-reactions' data-reply-to-id = "<%=post.id%>">
        <%= render 'forum/reactions/show', post: post %>
        <span class = 'vertical-divider'> · </span>
        <a href = 'javascript:void(0);' data-post-id=<%=post.id%> class = 'reply-to-post' onClick='insertReplyFormAfter($(this).parent()); return false'> Reply</a>
        <% if post.author_id == current_member.id %>
          <span class = 'vertical-divider'> · </span>
          <a href = 'javascript:void(0);' data-post-id=<%=post.id%> class = 'edit-post' onClick='editPost($(this).parent().parent()); return false'> Edit</a>
          <span class = 'vertical-divider'> · </span>
          <%= link_to 'Delete', "/forum/channels/#{post.channel_id}/posts/#{post.id}", remote: true, method: :delete, data: {post_id: post.id}, class: 'delete-post' %>
        <% end %>
      </div>
    </div>
    <div class = 'post-<%=post.id%>-replies'>
      <% post.replies.each do |reply| %>
        <%= render 'forum/posts/reply', reply: reply %>
      <% end %>
    </div>
  </div>
</div>

app/views/forum/posts/create.js.erb
$('.new-post-content').val('');
$('.new-reply').addClass('hide');
<% if @post.depth == 0 %>
    post = "<%= j (render 'forum/posts/show', post: @post) %>"
    $('.posts-container').append(post);
    $('.posts-container').animate({scrollTop: $('.posts-container').prop('scrollHeight')}, 100);
<% else %>
    post = "<%= j (render 'forum/posts/reply', reply: @post) %>"
    $('.post-<%=@parent_id.to_i%>-replies').append(post);
    $('.post-<%=@parent_id.to_i%>-replies').animate({ scrollTop: $('.post-<%=@parent_id.to_i%>-replies').prop("scrollHeight")}, 100);
<% end %>

app/views/forum/posts/destroy.js.erb
removeCrudFormsFromPost(<%=@post.id%>);
$('[data-post-id="<%=@post.id%>"]').remove();

app/views/forum/posts/error.js.erb
$('.flash-container').html("<%= j render 'layouts/flash_messages'%>");
setTimeout(hideFlash, 3000);

app/views/forum/posts/update.js.erb
elem = $('[data-post-id="<%=@post.id%>"] .post-content').first()
elem.text("<%= @post.content %>")
elem.show();
$('.edit-post-container').addClass('hide');