config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :members, controllers: { registrations: 'members/registrations', sessions: 'members/sessions' }
  devise_scope :member do
    get 'members/sign_out' => 'members/sessions#destroy'
    get 'members'          => 'members#index'
    post 'member/email_info' => 'members/registrations#email'
  end

  resources :messages, only: [:create] # TODO - this controller doesn't exist
  get '/rush' => 'rush#index'
  get '/tweets' => 'tweets#index'
  namespace :calendar do
    resources :events, only: %i[index show]
  end
  get '/calendar' => 'calendar/events#index'

  get '/projects/:project_id/donations/new' => 'donations#new'
  get '/projects/:project_id/donations'     => 'donations#index'
  post '/projects/:project_id/donations'    => 'donations#create'
  get '/projects_and_donations'             => 'projects#index'
  resources :projects, only: [:edit, :create, :destroy, :update] do
    post '/complete'                        => 'projects#complete'
  end
  get '/alumni'                             => 'alumni#index'
  resources 'roles', only: %i[edit update]
  resources 'pictures', only: %i[create destroy]
  resources 'unassociated_pictures', only: %i[create destroy]
  get '/profile'                            => 'members#edit'
  patch '/profile'                          => 'members#update'
  get '/members/sign_out'                   => 'members/sessions#destroy'

  namespace :forum do
    get '/'                              => 'channels#index'
    resources :channels, only: [:create, :update, :new, :destroy, :show] do
      resources :posts, only: [:create, :update, :destroy] do
        resources :reactions, only: [:create, :destroy]
      end
    end
  end
  if Rails.env.production?
    require 'sidekiq/web'
    authenticate :member, lambda { |m| m.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :identify_resource, :set_admin_flag, :authorize

  def create
    new_pictures = @resource.add_pictures_from_io(params[:files])
    render json: {
      newHTML: render_to_string(partial: 'index', locals:
                                { pictures: @resource.pictures, resource: @resource }).html_safe,
      newPicture: new_pictures.last.gsub(File.join(Rails.root, 'public'), ''),
      resourceClass: @resource.class.to_s,
      resourceId: @resource.id
    }
  end

  def destroy
    file = Rails.root.join("public/#{URI.decode(params[:id])}")
    render(nothing: true, status: 404) unless File.exist?(file)
    File.delete(file)
  end

  private

  def identify_resource
    @resource = Object.const_get(params[:resource_type]).find(params[:resource_id])
  end

  def authorize
    render nothing: true, status: 403 unless @admin_flag || @resource == current_member
  end
end

app/views/pictures/_index.html.erb
<div id='image-carousel-<%="#{resource.class}-#{resource.id}"%>' class='carousel slide' data-ride='carousel' data-interval="false">
  <% if pictures.count > 1 || @admin_flag %>
    <ol class='carousel-indicators'>
      <% pictures.each_with_index do |picture, i| %>
        <li data-target='#image-carousel-<%="#{resource.class}-#{resource.id}"%>' data-slide-to='<%=i%>' data-picture-url='<%=URI.encode(picture)%>' class=<%='active' if i == 0%>></li>
      <% end %>
      <% if @admin_flag %>
        <li data-target='#image-carousel-<%="#{resource.class}-#{resource.id}"%>' data-slide-to='<%=pictures.count%>' class=<%='active' if pictures.empty?%>></li>
      <% end %>
    </ol>
  <% end %>

  <div class='carousel-inner' role='listbox'>
    <% pictures.each_with_index do |picture, i| %>
      <div class='item image-container <%='active' if i == 0%>' data-picture-url='<%=URI.encode(picture)%>'>
        <%= image_tag picture %>
        <% if @admin_flag || @owner_flag %>
          <%= link_to picture_path(picture.gsub('.', '%2E'), resource_type: resource.class, resource_id: resource.id, format: :js), remote: true, method: :delete, class: 'delete-picture' do %>
            <i class = 'fa fa-times-circle-o'></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <% if @admin_flag || (@owner_flag && pictures.empty?)%>
      <div class='item image-container <%='active' if pictures.empty?%>'>
        <a href='javascript:void(0);' class='fileupload-mask fileupload' type="file" name="pictures[]" data-url=<%="/pictures.js?resource_type=#{resource.class}&resource_id=#{resource.id}"%> multiple=true>
          <%= image_tag 'upload_file.png' %>
        </a>
      </div>
    <% end %>
  </div>

  <% if pictures.count > 1 || @admin_flag %>
    <a class='left carousel-control' href='#image-carousel-<%="#{resource.class}-#{resource.id}"%>' role='button' data-slide='prev'>
      <span class='fa fa-chevron-left' aria-hidden='true'></span>
      <span class='sr-only'>Previous</span>
    </a>
    <a class='right carousel-control' href='#image-carousel-<%="#{resource.class}-#{resource.id}"%>' role='button' data-slide='next'>
      <span class='fa fa-chevron-right' aria-hidden='true'></span>
      <span class='sr-only'>Next</span>
    </a>
  <% end %>
</div>

app/views/pictures/destroy.js.erb
activeIndex = $('#image-carousel-<%="#{@resource.class}-#{@resource.id}"%> div.active').index();
$("[data-picture-url='<%= URI.encode(params[:id]).gsub('%252E', '.') %>']").remove();
var nextElement = $('#image-carousel-<%="#{@resource.class}-#{@resource.id}"%> .item')[activeIndex + 1] || $('#image-carousel-<%="#{@resource.class}-#{@resource.id}"%> .item')[activeIndex - 1];
$(nextElement).addClass('active');

app/views/pictures/new.html.erb
<div id='image-carousel' class='carousel slide' data-ride='carousel' data-interval="false" data-resource-id=<%= @resource.id %>>
  <% if @pictures.count > 1 %>
    <ol class='carousel-indicators'>
      <% @pictures.each_with_index do |picture, i| %>
        <li data-target='#image-carousel' data-slide-to='<%=i%>' data-picture-url='<%=URI.encode(picture)%>' class=<%='active' if i == 0%>></li>
      <% end %>
      <li data-target='#image-carousel' data-slide-to='<%=@pictures.count%>'></li>
    </ol>
  <% end %>

  <div class='carousel-inner' role='listbox'>
    <% @pictures.each_with_index do |picture, i| %>
      <div class='item image-container <%='active' if i == 0%>' data-picture-url='<%=URI.encode(picture)%>'>
        <%= image_tag picture %>
        <%= link_to picture_path(picture.gsub('.', '%2E'), format: :js), remote: true, method: :delete, class: 'delete-picture' do %>
          <i class = 'fa fa-times-circle-o'></i>
        <% end %>
      </div>
    <% end %>
    <div class='item image-container'>
      <a href='javascript:void(0);' class='fileupload-mask' data-form-data='{"script": "true"}' data-remote='true' id="fileupload" type="file" name="pictures[]" data-url=<%="/pictures.js?resource_type=#{@resource.class}&resource_id=#{@resource.id}"%> multiple=true>
        <%= image_tag 'upload_file.jpeg' %>
      </a>
      </div>
    </div>

    <% if @pictures.count > 1 %>
      <a class='left carousel-control' href='#image-carousel' role='button' data-slide='prev'>
        <span class='fa fa-chevron-left' aria-hidden='true'></span>
        <span class='sr-only'>Previous</span>
      </a>
      <a class='right carousel-control' href='#image-carousel' role='button' data-slide='next'>
        <span class='fa fa-chevron-right' aria-hidden='true'></span>
        <span class='sr-only'>Next</span>
      </a>
    <% end %>
  </div>